runtime: python310
instance_class: F1

entrypoint: gunicorn -b :$PORT --worker-class uvicorn.workers.UvicornWorker main:app

env_variables:
  PORT: "8080"

automatic_scaling:
  max_instances: 10

handlers:
- url: /.*
  script: auto
